name: ci-workflow-common

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        working-directory: ./server
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: make test
        working-directory: ${{env.working-directory}}
       
        

